apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: ap-southeast-1

nodeGroups:
  - name: ng1
    instanceType: t2.micro
    desiredCapacity: 3
    ssh:
        publicKeyName: eks
  - name: ng2
    minSize: 1
    maxSize: 3
    instancesDistribution:
      maxPrice: 0.017
      instanceTypes: ["t2.micro"] # At least one instance type should be specified
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 50
      spotInstancePools: 2
    ssh:
        publicKeyName: eks
   

